### ISSUE TITLE
Incompatible with Python-3.11: ValueError: invalid mode: 'rUb'

### ISSUE THREAD

**Issue by yurivict** [milkmiruku/stegosaurus#7]
```
===>  Configuring for stegosaurus-lv2-0.0.3
Waf: The wscript in '/wrkdirs/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-543a95d' is unreadable
Traceback (most recent call last):
  File "/wrkdirs/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-543a95d/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/wrkdirs/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-543a95d/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-543a95d/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Context.py", line 349, in load_module
    code=Utils.readf(path,m='rU',encoding=encoding)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/audio/stegosaurus-lv2/work/stegosaurus-543a95d/.waf3-2.0.10-cf8ca5fa84387374f6d66295baab59ec/waflib/Utils.py", line 141, in readf
    with open(fname,m)as f:
         ^^^^^^^^^^^^^
ValueError: invalid mode: 'rUb'
```

The 'U' flag has been deprecated in Python-3.11.

FreeBSD 14.0

**Comment by yurivict** [comment]
@mxmilkiib Any chance to fix this?

**Comment by mxmilkiib** [comment]
Not sure how, I didn't create it, dont have enough time/energy to investigate currently, but can accept any patch/PR that might come along!

**Comment by yurivict** [comment]
'rUb' needs to lose 'U', but even after this it still fails with some other error.
The bundled waf needs to be replaced with the new version, and the remaining issues need to be fixed.
I can't investigate this, I can only report bugs at the moment.
